In [31]:
import pandas as pd
import datetime

### Imports above, DF creation below

In [33]:
traffic_df = pd.read_csv('../Data/Traffic_Accidents.csv', low_memory=False)

In [52]:
covid_df = pd.read_excel('../Data/Covid_county.XLSX')

In [35]:
Metro_df = pd.read_csv('../Data/Metro_Nashville_Police_Department_Incidents.csv')

In [36]:
dui_df = pd.read_excel('../Data/Dui_arrests.xlsx')

# Traffic cleaning

### Par down to Nashville, Drop unnecessary columns

In [37]:
nash_traffic_df = traffic_df[traffic_df['City'] == 'NASHVILLE']
nash_traffic_df = nash_traffic_df.drop(columns = ['Collision Type Code', 'RPA', 'Precinct', 'Illumination Description', 'Illumination Code', 'Weather Code', 'Weather Description', 'Reporting Officer', 'Mapped Location', 'Harmful Code'])

### Creation of month and year columns for sorting

In [38]:
traffic_date = pd.to_datetime(nash_traffic_df['Date and Time'])
nash_traffic_df['Date and Time'] = traffic_date

In [39]:
nash_traffic_df['Month'] = nash_traffic_df['Date and Time'].dt.month
nash_traffic_df['Year'] = nash_traffic_df['Date and Time'].dt.year

In [40]:
nash_traffic_df['Month'] = nash_traffic_df['Month'].astype(str)
nash_traffic_df = nash_traffic_df.sort_values(by='Date and Time')
nash_traffic_df['Month'] = nash_traffic_df['Month'].replace(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])
nash_traffic_df

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Harmful Description,Street Address,City,State,ZIP,Latitude,Longitude,Month,Year
12173,20140004123,2014-01-01 00:00:00,1.0,0.0,0,False,True,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,BUILDING,1604 JEFFERSON ST,NASHVILLE,TN,37208.0,36.1705,-86.8033,January,2014
7778,20140000134,2014-01-01 00:30:00,2.0,0.0,0,False,True,SIDESWIPE - SAME DIRECTION,MOTOR VEHICLE IN TRANSPORT,I 24 W & MURFREESBORO PIKE,NASHVILLE,TN,37217.0,36.1368,-86.7268,January,2014
17114,20140000148,2014-01-01 00:30:00,1.0,3.0,0,False,False,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,PEDESTRIAN,1ST AVE S & DEMONBREUN ST,NASHVILLE,TN,37201.0,36.1603,-86.7731,January,2014
14553,20140000155,2014-01-01 00:40:00,2.0,0.0,0,False,False,REAR END,MOTOR VEHICLE IN TRANSPORT,1011 DEMONBREUN ST,NASHVILLE,TN,37203.0,36.1560,-86.7830,January,2014
6288,20140000193,2014-01-01 00:55:00,1.0,0.0,0,False,True,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,BUILDING,3304 DICKERSON PIKE,NASHVILLE,TN,37207.0,36.2352,-86.7583,January,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218763,20200795425,2020-12-30 20:05:00,1.0,0.0,0,NaN,False,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CONCRETE TRAFFIC BARRIER,MM 202 7 I 40,NASHVILLE,TN,37209.0,36.1468,-86.8781,December,2020
218766,20200795463,2020-12-30 20:46:00,2.0,1.0,0,NaN,False,ANGLE,MOTOR VEHICLE IN TRANSPORT,CLIFTON AV & 21ST AVN,NASHVILLE,TN,37209.0,36.1576,-86.8071,December,2020
218750,20200795498,2020-12-30 21:20:00,2.0,0.0,0,NaN,False,ANGLE,MOTOR VEHICLE IN TRANSPORT,FRANKLIN PKE & OLD HICKORY BLVD,NASHVILLE,TN,37220.0,36.0377,-86.7865,December,2020
218772,20200795520,2020-12-30 21:42:00,1.0,0.0,0,True,False,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CONCRETE TRAFFIC BARRIER,MM 213 0 I 40,NASHVILLE,TN,37210.0,36.1407,-86.7323,December,2020
218762,20200795557,2020-12-30 21:56:00,2.0,3.0,0,NaN,False,UNKNOWN,MOTOR VEHICLE IN TRANSPORT,BRICK CHURCH PKE & EWING LN,NASHVILLE,TN,37207.0,36.2326,-86.7814,December,2020

### Drop 2013

In [41]:
nash_traffic_df = nash_traffic_df[nash_traffic_df['Year'] > 2013]
nash_traffic_df

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Harmful Description,Street Address,City,State,ZIP,Latitude,Longitude,Month,Year
12173,20140004123,2014-01-01 00:00:00,1.0,0.0,0,False,True,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,BUILDING,1604 JEFFERSON ST,NASHVILLE,TN,37208.0,36.1705,-86.8033,January,2014
7778,20140000134,2014-01-01 00:30:00,2.0,0.0,0,False,True,SIDESWIPE - SAME DIRECTION,MOTOR VEHICLE IN TRANSPORT,I 24 W & MURFREESBORO PIKE,NASHVILLE,TN,37217.0,36.1368,-86.7268,January,2014
17114,20140000148,2014-01-01 00:30:00,1.0,3.0,0,False,False,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,PEDESTRIAN,1ST AVE S & DEMONBREUN ST,NASHVILLE,TN,37201.0,36.1603,-86.7731,January,2014
14553,20140000155,2014-01-01 00:40:00,2.0,0.0,0,False,False,REAR END,MOTOR VEHICLE IN TRANSPORT,1011 DEMONBREUN ST,NASHVILLE,TN,37203.0,36.1560,-86.7830,January,2014
6288,20140000193,2014-01-01 00:55:00,1.0,0.0,0,False,True,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,BUILDING,3304 DICKERSON PIKE,NASHVILLE,TN,37207.0,36.2352,-86.7583,January,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218763,20200795425,2020-12-30 20:05:00,1.0,0.0,0,NaN,False,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CONCRETE TRAFFIC BARRIER,MM 202 7 I 40,NASHVILLE,TN,37209.0,36.1468,-86.8781,December,2020
218766,20200795463,2020-12-30 20:46:00,2.0,1.0,0,NaN,False,ANGLE,MOTOR VEHICLE IN TRANSPORT,CLIFTON AV & 21ST AVN,NASHVILLE,TN,37209.0,36.1576,-86.8071,December,2020
218750,20200795498,2020-12-30 21:20:00,2.0,0.0,0,NaN,False,ANGLE,MOTOR VEHICLE IN TRANSPORT,FRANKLIN PKE & OLD HICKORY BLVD,NASHVILLE,TN,37220.0,36.0377,-86.7865,December,2020
218772,20200795520,2020-12-30 21:42:00,1.0,0.0,0,True,False,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CONCRETE TRAFFIC BARRIER,MM 213 0 I 40,NASHVILLE,TN,37210.0,36.1407,-86.7323,December,2020
218762,20200795557,2020-12-30 21:56:00,2.0,3.0,0,NaN,False,UNKNOWN,MOTOR VEHICLE IN TRANSPORT,BRICK CHURCH PKE & EWING LN,NASHVILLE,TN,37207.0,36.2326,-86.7814,December,2020

# COVID cleaning

### Par down to Davidson, change column names, drop superfluous information

In [53]:
covid_df = covid_df[covid_df['COUNTY'] == 'Davidson']
covid_df = covid_df.drop(columns = ['TOTAL_CONFIRMED', 'NEW_CONFIRMED', 'TOTAL_PROBABLE', 'NEW_PROBABLE', 'NEW_NEG_TESTS', 'NEG_TESTS', 'TOTAL_TESTS', 'NEW_TESTS', 'POS_TESTS', 'NEW_POS_TESTS', 'TOTAL_DEATHS_BY_DOD'])
covid_df

,DATE,COUNTY,TOTAL_CASES,NEW_CASES,NEW_DEATHS,TOTAL_DEATHS,NEW_RECOVERED,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_INACTIVE_RECOVERED,TOTAL_INACTIVE_RECOVERED,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED
2,2020-03-06,Davidson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2020-03-08,Davidson,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2020-03-09,Davidson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2020-03-10,Davidson,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2020-03-11,Davidson,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27280,2020-12-29,Davidson,59694.0,349.0,7.0,556.0,NaN,NaN,-433.0,5933.0,775.0,53205.0,15.0,1587.0
27377,2020-12-30,Davidson,60757.0,1063.0,8.0,564.0,NaN,NaN,371.0,6304.0,684.0,53889.0,5.0,1592.0
27474,2020-12-31,Davidson,61497.0,740.0,6.0,570.0,NaN,NaN,106.0,6410.0,628.0,54517.0,9.0,1601.0
27571,2021-01-01,Davidson,61974.0,477.0,1.0,571.0,NaN,NaN,-143.0,6267.0,619.0,55136.0,1.0,1602.0
27668,2021-01-02,Davidson,62841.0,867.0,1.0,572.0,NaN,NaN,263.0,6530.0,603.0,55739.0,0.0,1602.0

In [54]:
covid_df.columns = ['Date', 'County', 'Total Cases', 'New Cases', 'New Deaths', 'Total Deaths', 'New Recovered', 'Total Recovered', 'New Active', 'Total Active', 'New Inactive Recovered', 'Total Inactive Recovered', 'New Hospitalized', 'Total Hospitalized']

# Metro Incidients Cleaning

### Par down to Nashville and DUI's, drop unnecessary columns

In [22]:
# 90D code for Driving under the Influence
metro_df = Metro_df[Metro_df['Offense NIBRS'] == '90D']
metro_df = metro_df.drop(columns = ['Victim Ethnicity', 'Victim Race', 'Victim Description', 'Victim Type', 'Victim County Resident', 'Victim Gender', 'Victim Number', 'Weapon Description', 'Weapon Primary'])
metro_df.sort_values(by='Incident Occurred')
#dataset is incomplete, definitely more than 97 DUI's in nashville in the last 7 years

,Primary Key,Incident Number,Report Type,Report Type Description,Incident Status Code,Incident Status Description,Investigation Status,Incident Occurred,Incident Reported,Incident Location,...,ZIP Code,RPA,Zone,Location Code,Location Description,Offense Number,Offense NIBRS,Offense Description,Domestic Related,Mapped Location
272629,20140014502_11,20140014502,S,SUSPECT,A,CLEARED BY ARREST,Closed,01/05/2014 03:30:00 AM,01/05/2014 08:19:00 AM,GRAYLYNN DR & LEBANON PIKE,...,37214.0,NaN,NaN,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE,False,POINT (-86.674 36.17)
456796,20160034716_11,20160034716,D,DISPATCHED,A,CLEARED BY ARREST,Closed,01/07/2016 06:49:00 PM,01/11/2016 07:38:00 PM,MT PISGAH RD & BRYCE RD,...,37211.0,NaN,NaN,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE,False,NaN
112293,20160049650_11,20160049650,D,DISPATCHED,O,OPEN,Open,01/15/2016 03:55:00 PM,01/15/2016 09:12:00 PM,ELM HILL PIKE,...,NaN,NaN,NaN,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE,False,POINT (-86.66 36.15)
274274,20140092171_11,20140092171,D,DISPATCHED,A,CLEARED BY ARREST,Closed,01/26/2014 09:00:00 AM,01/26/2014 02:15:00 PM,ACADEMY RD & SANITARIUM RD,...,37115.0,NaN,NaN,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE - 2ND OFFENSE,False,POINT (-86.68 36.254)
185690,20130083276_11,20130083276,S,SUSPECT,A,CLEARED BY ARREST,Closed,01/27/2013 10:30:00 PM,01/27/2013 10:30:00 PM,200 JAMES ROBERTSON PKWY,...,37201.0,NaN,NaN,14.0,"HOTEL, MOTEL, ETC.",1.0,90D,DRIVING UNDER THE INFLUENCE,False,POINT (-86.779 36.168)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816915,20190860435_21,20190860435,S,SUSPECT,A,CLEARED BY ARREST,Closed,11/29/2019 02:35:00 AM,11/29/2019 05:38:00 AM,600 WHISPERING HILLS DR,...,37211.0,8659.0,835.0,13.0,"HIGHWAY, ROAD, ALLEY",2.0,90D,DRIVING UNDER INFLUENCE LIQUOR,False,POINT (-86.728 36.065)
432593,20151114186_11,20151114186,D,DISPATCHED,A,CLEARED BY ARREST,Closed,12/06/2015 02:15:00 AM,12/06/2015 06:30:00 AM,2900 CREEKBEND DR,...,37207.0,3045.0,621.0,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE,False,POINT (-86.798 36.235)
612113,20171123291_11,20171123291,S,SUSPECT,A,CLEARED BY ARREST,Closed,12/25/2017 02:45:00 AM,12/25/2017 03:26:00 AM,1900 LEBANON PIKE,...,37210.0,9019.0,513.0,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE,False,POINT (-86.709 36.157)
501604,20171130148_21,20171130148,S,SUSPECT,A,CLEARED BY ARREST,Closed,12/28/2017 01:12:00 AM,12/28/2017 04:01:00 AM,12TH AVE S & MCGAVOCK ST,...,37203.0,4081.0,423.0,13.0,"HIGHWAY, ROAD, ALLEY",2.0,90D,DRIVING UNDER INFLUENCE LIQUOR,False,POINT (-86.787 36.156)
513304,20171132638_11,20171132638,D,DISPATCHED,A,CLEARED BY ARREST,Closed,12/28/2017 10:30:00 PM,12/29/2017 12:29:00 AM,6TH AVE N & CHURCH ST,...,37219.0,4143.0,411.0,13.0,"HIGHWAY, ROAD, ALLEY",1.0,90D,DRIVING UNDER THE INFLUENCE,False,POINT (-86.781 36.163)

# DUI Arrests Cleaning

### Par down to Nashville, drop unnecessary columns / personal data

In [19]:
nash_dui_df = dui_df[dui_df['Arrest Location'].str.contains('NASHVILLE')]
nash_dui_df = nash_dui_df[['Arrest Number', 'CHARGE', 'Arrest Date', 'Arrest Location']]

### Clean up "date" column / add and clean month column and year column

In [26]:
dui_date = pd.to_datetime(nash_dui_df['Arrest Date'], format='%Y%m%d')
nash_dui_df['Arrest Date'] = dui_date
nash_dui_df['Month'] = nash_dui_df['Arrest Date'].dt.month
nash_dui_df['Year'] = nash_dui_df['Arrest Date'].dt.year

In [28]:
nash_dui_df['Month'] = nash_dui_df['Month'].astype(str)
nash_dui_df = nash_dui_df.sort_values(by='Arrest Date')
nash_dui_df['Month'] = nash_dui_df['Month'].replace(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])
nash_dui_df

,Arrest Number,CHARGE,Arrest Date,Arrest Location,Month,Year
3,100006124,5405,2010-01-01,2211 WEST END AVE NASHVILLE TN 37203 ...,January,2010
26,100006146,5406,2010-01-01,21ST AVE & GRAND AVE NASHVILLE TN 37203 ...,January,2010
25,100006121,5406,2010-01-01,PARAGON MILLS RD & TRAVIS DR NASHVILLE TN 3721...,January,2010
24,100008098,5405,2010-01-01,WEST END & 24TH AV S NASHVILLE TN ...,January,2010
23,100008095,5405,2010-01-01,CONFERENCE DR & WINDSOR GREEN NASHVILLE TN ...,January,2010
...,...,...,...,...,...,...
33196,200028858,5405,2020-12-27,GALLATIN PIKE & GREENFIELD AVE NASHVILLE TN 37...,December,2020
33195,200028850,5405,2020-12-27,622 MCGAVOCK PIKE NASHVILLE TN 37214 ...,December,2020
33198,200028977,5405,2020-12-29,NOLENSVILLE PIKE NASHVILLE TN 37211 ...,December,2020
33199,200028978,5405,2020-12-30,1818 ALBION ST NASHVILLE TN 37208 ...,December,2020
33200,200028984,5405,2020-12-30,HAYWOOD LN & NOLENSVILLE PIKE NASHVILLE TN 372...,December,2020

### Par down to 2014 and later

In [30]:
nash_dui_df = nash_dui_df[nash_dui_df['Year'] > 2013]

### Exports

In [56]:
nash_traffic_df.to_csv('../Data/Cleaned_data/nash_traffic.csv')

In [58]:
covid_df.to_csv('../Data/Cleaned_data/Davidson_Covid.csv')

In [59]:
nash_dui_df.to_excel('../Data/Cleaned_data/nash_dui.xlsx')